CREATE TABLE `mock_api` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `feign_value` varchar(255) DEFAULT NULL COMMENT '请求url',
  `url` varchar(512) DEFAULT NULL COMMENT '请求url',
  `response_body` text COMMENT '返回内容 ',
  `template_engine` varchar(255) DEFAULT NULL COMMENT '模板引擎(freeMark,default)',
  `remark` varchar(255) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_delete` int(1) DEFAULT '0',
  `delete_by` varchar(100) DEFAULT NULL,
  `delete_time` datetime DEFAULT NULL,
  `is_cancel` tinyint(4) DEFAULT NULL,
  `version` tinyint(4) DEFAULT NULL,
  `udf_1` varchar(50) DEFAULT NULL,
  `udf_2` varchar(50) DEFAULT NULL,
  `udf_3` varchar(50) DEFAULT NULL,
  `udf_4` varchar(50) DEFAULT NULL,
  `udf_5` varchar(50) DEFAULT NULL,
  `udf_6` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;