server:
  port: 8888


spring:
  # DataSource Config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/my_shares?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: smile@123
    #HikariCP数据库连接池（连接池需要根据实际情况进行配置）
    hikari:
      #连接池名称
      pool-name: smilehappiness_HikariCP
      #最小空闲连接数量
      minimum-idle: 10
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 120000
      #连接池最大连接数，默认是10
      maximum-pool-size: 20
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.smilehappiness.*.model,com.smilehappiness.*.mapper,com.smilehappiness.*.entity
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    map-underscore-to-camel-case: true
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
    use-generated-keys: true
    default-executor-type: reuse
    defaultStatementTimeout: 1000
    jdbc-type-for-null: null
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1


swagger:
  groupName: ${spring.application.name}
  enabled: true
  title: 后台接口文档
  base-package: com.smilehappiness
  description: 后台管理框架
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  #接口文档地址，后续可以链接接口文档服务地址
  terms-of-service-url: http://localhost:6666/doc.html
  contact: xxx@163.com
